### ISSUE TITLE
특정 자바 버젼을 사용해야하나요?

### ISSUE THREAD

**Issue by keepcosmos** [jun85664396/twkorean-ruby#1]
현재 OS X El Capitan을 사용하는 중인데요, 
Java Version 이슈가 좀 있는거 같네요, 

```{shell}
UnsupportedClassVersionError: com/twitter/penguin/korean/TwitterKoreanProcessorJava$Builder : Unsupported major.minor version 51.0
	from /Users/Keepcosmos/.rvm/gems/ruby-2.2.3/gems/twkorean-0.0.3/lib/twkorean/twitter_korean_text.rb:14:in `import'
	from /Users/Keepcosmos/.rvm/gems/ruby-2.2.3/gems/twkorean-0.0.3/lib/twkorean/twitter_korean_text.rb:14:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /Users/Keepcosmos/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'
```
어떤 문제인가요?

아 그리고,
현재 프로젝트에서 gem을 사용하려고 하는데,
버전업 / 테스트 / 기능추가 등 앞으로 지속적으로 관리될 예정인지 궁금합니다.

**Comment by jun85664396** [comment]
안녕하세요.
버전업과 테스트는 [twitter-korean-text-4.4](https://github.com/twitter/twitter-korean-text/tree/korean-text-4.4)에 맞춰서 업데이트하였습니다.
프로젝트는 비정기적으로 관리 될 거 같습니다...
OS X El Capitan 버전 이슈에 관련해서는 [rjb](https://github.com/arton/rjb)에서 발생하는 거 같습니다.
감사합니다.
